
version: 0.2



phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install streamlit
  build:
    commands:
      - echo "pycodestyle found no issues!"
      - streamlit run app.py

  
